name: Docker Image CI release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file .devcontainer/Dockerfile --tag my-image-name:$(date +%s)

    - name: Run Build optimized binary
      run: make release

    - name: Move binary to root directory
      run: mv target/release/rust_sqlite_demo ./ 

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: rust-binary
        path: ./rust_sqlite_demo  

    - run: echo "🍏 This job's status is ${{ job.status }}."




